version: 3
services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: dc_bot
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  server:
    build:
      context: .
      dockerfile: Dockerfile
